#!/usr/bin/python
# Copyright © 2012 Felix Richter <wtfpl@syntax-fehler.de>
# This work is free. You can redistribute it and/or modify it under the
# terms of the Do What The Fuck You Want To Public License, Version 2,
# as published by Sam Hocevar. See the COPYING file for more details.

from jsonpath_rw import parse
import json
import sys
if len(sys.argv) < 2:
    print("""usage: %s jsonpath
path can be:
    atomics:
        $              - root object
        `this`         - current object

    operators:
        path1.path2    - same as xpath /
        path1|path2    - union
        path1..path2   - somewhere in between

    fiels:
        fieldname       - field with name
        *               - any field
        [_start_?:_end_?] - array slice
        [*]             - any array index
""")
    sys.exit(1)
path = sys.argv[1]
print(" ".join([str(match.value) for match in parse(path).find(
    json.load(sys.stdin))]))
